### ISSUE TITLE
Stork fails post on missing gitsha's

### ISSUE THREAD

**Issue by brendanmcfarland** [mapbox/stork#27] opened 2017-10-20 18:53 UTC
Ran into a stork alarm today with some stork errors regarding an "unprocessable entity"

sample:
``` 
{ HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.e (/var/task/node_modules/got/index.js:123:13)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  message: 'Response code 422 (Unprocessable Entity)',
  host: 'api.github.com',
  hostname: 'api.github.com',
  method: 'POST',
  path: <repo path>,
  statusCode: 422,
  statusMessage: 'Unprocessable Entity' }
```
@rclark determined that the end of that path is a [sha](https://github.com/mapbox/stork/blob/master/lambda.js#L477), and some quick investigating it became clear that sha was not present on github.

It looks like stork will error when a sha is force pushed or deleted.

cc: @rclark 

edited: removed repo path (@kellyoung)

**Comment by rclark** [comment] 2017-10-20 20:42
This happened as part of stork's `status` lambda function. This function receives cloudwatch events indicating progression of the build that AWS codebuild is running. Its job is to report that status update as an indication on a PR. 

My guess is that commit `b9c63f8fb15bddf16a366f64dbc8d92685cd3c26` hit and was quickly force-pushed over. By the time stork was trying to report about it, the sha had been erased from history. 

In that situation, we want the application to ignore the error. The problem is that I don't see a way to differentiate between this situation and some other failure state. Like if stork sends a bad payload the the github API, the resulting response (422) would be the same.

**Comment by vsmart** [comment] 2017-10-26 22:12
Got this alarm again today for https://github.com/mapbox/mapbox-gl-native.

**Comment by rclark** [comment] 2017-10-31 01:09
To try and satisfy this and also #30, the status function should:

1. Do the POST
2. if there's any failure, check that the SHA it has an update for exists in github
2. if it exists, the lambda function should throw an error
3. if it does not exist, the lambda function should just exit

cc @brendanmcfarland

**Comment by vsmart** [comment] 2018-06-28 20:49
This reappeared today. `422` "unprocessable entity" response from Github, on 3 commit shas that were not found. Seems like there is an edge case that is not covered yet by #31.  

Update: from the logs, it definitely looks like the error should be caught by our if-condition. I've  added additional logging in #42  to try to identify the cause.

**Comment by vsmart** [comment] 2018-06-29 14:14
The new logs added in #42 revealed that for this specific repo, even the "get-commit" call we make to check whether the commit still exists, return a `422`. 
This seems to happen whenever a PR is merged, likely with squashed commits.

I have de-registered and re-registered the repo, in case there is some strange stork subscription error at play here. 

From looking at response logs, I could not figure out why the request was unprocessable 🤔

**Comment by emilymcafee** [comment] 2018-07-05 00:04
> revealed that for this specific repo, even the "get-commit" call we make to check whether the commit still exists, return a 422.

I believe this is an issue with the Github API, and potentially something about the headers we are sending with the request are masking the response that you get elsewhere saying that the commit is missing. For example, if you run the same request in the browser or using curl, you get

> $ curl https://api.github.com/repos/{owner}/{repo}/commits/{sha} -H "Authorization: token {token}" -i
> 
>
> HTTP/1.1 422 Unprocessable Entity
> Date: Thu, 05 Jul 2018 00:02:54 GMT
> Content-Type: application/json; charset=utf-8
> Content-Length: 178
> Server: GitHub.com
> Status: 422 Unprocessable Entity
>
>
> {
  "message": "No commit found for SHA: {sha}",
  "documentation_url": "https://developer.github.com/v3/repos/commits/#get-a-single-commit"
}

This is certainly very confusing. However, in all the errors we've seen recently from this condition, I've manually searched around the affected repo and have never found the commit - it appears to be gone.

I'm going to add another condition to catch this error...

**Closed as completed** 2018-07-05 17:01 UTC
